### ISSUE TITLE
CVE Scanning doesn't save the output after scan to the CVE testing

### ISSUE THREAD

**Issue by EPodvoiskyi** [R-s0n/ars0n-framework#11]
I am not sure why but after I executed the following command: python3 wildfire.py -S localhost -P 8000 --start --scan and I can see that nuclei scan is running there is no output in what pages exactly did it find potential flaws and in the CVE Testing at the front page there is zero cves after scan managed to find some

**Comment by DKrypt1337** [comment]
In my testing so far, I've seen that only once each section of the Nuclei scan, or each scan is complete, then you go refresh the page and they will show for that section. I've also noticed when adding another domain, and running a bridge scan it modified the original domain I already scanned. I just made a fork, and I'm going to look into improving the React side and do a pull request. I'd like to contribute to this for sure, it's an amazing tool!

**Comment by EPodvoiskyi** [comment]
For sure!
By the way are you using global script like called wildfire.py for nuclei scanning?

**Comment by DKrypt1337** [comment]
Yes, just need to do python3 wilfire.py --start --scan and let it go. After adding the domain in the local webapp of course.

**Comment by R-s0n** [comment]
@DKrypt1337 The PR looks great!!  I'm hoping to have my testing done so I can merge it within the next month.  Once that's done, I'll let you know @EPodvoiskyi so you can confirm this has solved the issue.  I can contest, though, that refreshing the page after the CVE scan is complete *should* resolve the issue in the meantime.  I'll be candid, I didn't put a ton of work into the front end 😅

**Comment by R-s0n** [comment]
This problem has been resolved in the Alpha launch.  Thank you for brining this up!
