### ISSUE TITLE
"Something went wrong!" error on installation.

### ISSUE THREAD

**Issue by Eaglevw** [R-s0n/ars0n-framework#14]
When running `python3 install.py` I receive a "Something went wrong!" error. 
I've tried installing on a fresh Kali build resulting in the same error.
I see the error pops up when it's trying to install Mongodb.
![Capture](https://github.com/R-s0n/ars0n-framework/assets/77943922/c1169888-df2e-4846-bcb7-e1dc3b6d2497)

**Comment by Eaglevw** [comment]
Tried a fresh VM using VMware and it worked. Installation completed and I can add a scope.
I am way to stupid to know what the error was lol, but I can work with vmware.

**Comment by R-s0n** [comment]
It's probably something going on with MongoDB.  I know it doesn't support several different processors.  I may end up ripping Mongo out for SQLite.  I would troubleshoot MongoDB, though, and see if you can get the service running.

**Comment by R-s0n** [comment]
I just pushed out an update, yesterday, that should resolve most of the MongoDB issues on Kali.  Please feel free to test it out.  If I don't hear in a month, I'll assume the issue is resolved.

Thank you!
