### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by dookofcrds** [R-s0n/ars0n-framework#16]
installing on parrot OS 

[+] Node is already installed.  Checking version...
[-] Current Node Version: v12
[!] Node 18 is NOT already installed.  Installing now...
[!] This can take 30+ minutes depending on your machine.
[!] Something went wrong!  Please try to run the installer again or open an issue on the repo...

**Comment by R-s0n** [comment]
This framework has only been tested on Kali.
