### ISSUE TITLE
Automatically Stopping the server

### ISSUE THREAD

**Issue by xgt6op** [R-s0n/ars0n-framework#2]
[+] Done!  Start: 14:27:19  |  Stop: 14:27:19

Automatically stopping

**Comment by Lesrad** [comment]
I had the same issue, resolved by running ./run.sh which seemed to fix it,

**Comment by R-s0n** [comment]
Interesting, can you give more information about how the server is "Automatically stopping"?  After you complete the install script, there is an option to run the server.  Any input to that prompt other than "Y" will result in the install script closing, which is what it looks like happened.  Either way, as Lesrad said, the run.sh script is designed to run both the client and server.  Let me add some quick notes to the README.  I promise I'll get something more informative built out as soon as I can.

**Comment by R-s0n** [comment]
@xgt6op The update I pushed out last night should solve the majority of edge cases that would have led to this issue.  Please let but know if this is still an issue, but I will close this as Resolved for now.
