### ISSUE TITLE
Results of a scan cannot be saved

### ISSUE THREAD

**Issue by visualmagix** [R-s0n/ars0n-framework#24]
Hi ars0n,

firstable you have a great idea and a framework. Unfortunately i cannot use it and i don't know if i miss something or it has something to do with Kali and the MongoDB version.

Installation works fine but after running the first scan i see the command output but don't the results in the Web GUI.

I make some observations and here are some points that i found out. Maybe i don't understand or i'm confused, but i want to to let you know what makes me confusing.

If you need further information on specific data i will do the best that i can to collect the needed data and will provide this for you.

Many thanks from Düsseldorf, Germany :)

In the run.sh script there's mongodb mentioned.

----------------------------------------------------------

#!/bin/bash

sudo systemctl enable mongodb 2>/dev/null
sudo systemctl start mongodb 2>/dev/null
node server/server.js &
cd client
npm run start

----------------------------------------------------------

But the only service/unit related to MongoDB is "mongod" and NOT "mongodb"

See results below

systemctl status mongodb
Unit mongodb.service could not be found.
                                                                             
┌──(root㉿kali)-[~]
└─# systemctl status mongod 
● mongod.service - MongoDB Database Server
     Loaded: loaded (/lib/systemd/system/mongod.service; enabled; preset: di>
     Active: active (running) since Wed 2023-09-20 05:42:49 EDT; 33min ago
       Docs: https://docs.mongodb.org/manual
   Main PID: 733 (mongod)
     Memory: 251.9M
        CPU: 17.600s
     CGroup: /system.slice/mongod.service
             └─733 /usr/bin/mongod --config /etc/mongod.conf

Sep 20 05:42:49 kali systemd[1]: Started mongod.service - MongoDB Database S>
Sep 20 05:42:49 kali mongod[733]: {"t":{"$date":"2023-09-20T09:42:49.475Z"},>

Next thing under "/etc/mongod.conf"

The port is 27017 and on your setup it's 8000. But if try to change it in the conf file to 27017 it doesn't work. Also the same way if a try it in the wildfire.py script.

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1

This is my kali version :

Linux kali 6.4.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.11-1kali1 (2023-08-21) x86_64 GNU/Linux

**Comment by R-s0n** [comment]
Thank you for all the information, @visualmagix!  Sorry the tool isn't working for you!  It definitely could be an issue with Mongo, but it could also be that the UI doesn't do a good job of refreshing itself on it's own yet.  Let's start with a few questions:

1. Are you able to add a domain to the framework?
2. Have you run a full scan using `python3 wildfire.py --start`
3. If the answer to the first two questions are yes, can you show me a screenshot of the dashboard when you refresh the page?

It's possible that you got a version that just has a bug in it.  I'll have a stable Alpha release out within a week or two.  Can you please also make sure that you are using the latest version?

Worst case, maybe you can join a stream and we can troubleshoot live?  Either way, we will get it running for ya!

**Comment by visualmagix** [comment]
Hi ars0n,

here's a bunch of screenshot regarding the dashboard and the possible execution of the python script. Also the log information that is created during the runtime of the client. Hopes this helps. 

I tryed a fresh new kali virtual-box image installation without any additional tools. Fresh kali, full-upgrade with apt and then cloning of your repo with the known installation process form your Youtube video. Nothing special. 

Adding targets over the website with the adding button works fine, also the scanning feature, but regardless of the scanning options and how i try it out many times it doesn't save the results on the dashboard. DNS, IP, Subnet, Vulnearbility results from nucli etc. Nothing.

Do you have any idea what i could try out or should i wait until your next release?


Many thanks for your help and your time.

Kind regards from germany

[arson-framework compilation!.txt](https://github.com/R-s0n/ars0n-framework/files/12869595/arson-framework.compilation.txt)
![Screenshot 2023-10-11 140901](https://github.com/R-s0n/ars0n-framework/assets/28691660/aa0de796-42de-4f5b-8b8b-b6f3313f615d)
![Screenshot 2023-10-11 140928](https://github.com/R-s0n/ars0n-framework/assets/28691660/9f5e323d-d9ec-4daf-8fff-c69a862052f2)
![Screenshot 2023-10-11 141037](https://github.com/R-s0n/ars0n-framework/assets/28691660/c8c4fd3e-a455-4b82-b344-35b59b10fbd4)

**Comment by R-s0n** [comment]
Everything looks good from what I can see.  Can you please try running `wildfire.py --start` against floqast.app?  Let the scan finish, then copy the last 10 lines of output from the CLI tool to show what happened when it stopped running?  Finally, after wildfire.py has finished, please refresh the web application and take a screenshot showing the dashboard.  That should give me everything I need to know how to help!

**Comment by quyenvuongu** [comment]
Hi @R-s0n,

I run into the issue with installation on fresh kali VM.
![image](https://github.com/R-s0n/ars0n-framework/assets/75088314/e9d0c101-5067-45fe-88c3-8399c8ae13f8)

Run debug.sh
![image](https://github.com/R-s0n/ars0n-framework/assets/75088314/1dd93992-947a-4760-97da-5a5d58f05928)

Regards,

**Comment by R-s0n** [comment]
@quyenvuongu Thank you for sharing this!  This could be what is causing the issue @visualmagix is getting.  If so, I believe I have resolved the issue.  Sorry about that!  I made the proxy mandatory when I was testing the Alpha release and must have forgotten to remove it.

That error message is caused because it's trying to route all the HTTP calls through Burp on 127.0.0.1:8080. This error occurs when Burp isn't running, but this shouldn't be mandatory. I just pushed a commit that should fix it.

A stable Alpha release will be available in the next week or so!

**Comment by visualmagix** [comment]
@R-s0n 
I get the same message regarding the proxy error lines. I thought this was not a critical one, as the scan could run through all the procedures and modules. It could finished the scan and i never think this has to do with the Burp Proxy connection. 

I will wait for your next release and thank you for your troubleshooting on this error. 

One question regarding Burp and ZED Attack Proxy. Do you test them both and could you also recommend ZAP or would you say Burp is the prefered option?


Many thanks

**Comment by visualmagix** [comment]
The new release and your changes work quit wonderful. I can see now the scan results and they're visible on the other pages as well. 

Many thanks for your work, efforts and your help.


All the best

**Comment by R-s0n** [comment]
Excellent!  Sorry, I'm just now seeing your last comment as well.  I just pushed a new commit that should be very stable.  I'm *very* close to putting the finishing touches on the Alpha!

"One question regarding Burp and ZED Attack Proxy. Do you test them both and could you also recommend ZAP or would you say Burp is the prefered option?"

I'll probably only do Burp to start, but if a good need for supporting ZAP comes up I'm definitely open to it.
