### ISSUE TITLE
Can only view ars0n dashboard when localhost

### ISSUE THREAD

**Issue by rootd4ddy** [R-s0n/ars0n-framework#27]
I recently made a docker container for ars0n framework so I can run it on one of my servers. The problem is the website is not fully accessible unless you are accessing it on localhost. Same goes for just a regular install. Switch to bridged adapter in vbox and try to access the website from the host box and you will see what I mean.

**Comment by R-s0n** [comment]
Yep, that's actually how the tool is designed.  At least for this phase of development.  I may choose to refactor the code so it can be run in the way you are describing, but not for at least a year or two.
