### ISSUE TITLE
server not starting 

### ISSUE THREAD

**Issue by Amal03-bit** [R-s0n/ars0n-framework#3]
![test](https://user-images.githubusercontent.com/61375692/222131439-20545225-6417-4618-a9e4-732521a16361.jpg)

**Comment by R-s0n** [comment]
Looks like you've already got a process running on port 8000, which is what the API uses.  You'll need to kill that process or change the port the API runs on.  You can use `netstat -tulpn | grep LISTEN` to see what ports you currently have open, along with the process that's using it.
