### ISSUE TITLE
Unable to install eror again and again

### ISSUE THREAD

**Issue by scriptkiddieeee** [R-s0n/ars0n-framework#50]
I m unable to install your framework on latest kali linux 
![Screenshot from 2024-01-07 20-30-22](https://github.com/R-s0n/ars0n-framework/assets/91931069/b2cc4949-1b6d-459a-8086-f1678e18b363)

**Comment by R-s0n** [comment]
You say it failed "again and again", what troubleshooting steps did you take between installation attempts?  Are you installing the framework on a clean installation of Kali Linux 2023.4?  Your version of Node is 20, which does not come on Kali Linux by default and my framework does not install that.  You will need to either remove Node 20 or change which version is called when you run the `node` command.

**Comment by scriptkiddieeee** [comment]
> You say it failed "again and again", what troubleshooting steps did you take between installation attempts? Are you installing the framework on a clean installation of Kali Linux 2023.4? Your version of Node is 20, which does not come on Kali Linux by default and my framework does not install that. You will need to either remove Node 20 or change which version is called when you run the `node` command.

I am using kali as a natively from 2 year i cant install clean installation but i will try with node 18 and let you know
