### ISSUE TITLE
i have error with amass running

### ISSUE THREAD

**Issue by Gngester** [R-s0n/ars0n-framework#57]
[ERROR] 2024-02-06 18:40:12.225713 | Fire-Starter.py -- Amass Exception: [Errno 2] No such file or directory: './temp/amass.tmp'
and i do not have this directory i tried to find it and nothing

**Comment by Gngester** [comment]
time="2024-02-07T04:33:13-05:00" level=warning msg="error reading config: open /home/test/.gau.toml: no such file or directory"

**Comment by Gngester** [comment]
Failed to load the configuration file: error unmarshalling datasources YAML: yaml: line 119: mapping values are not allowed in this context

**Comment by R-s0n** [comment]
Those are all just general warnings.  The amass error just means amass didn't find any subdomains.  I plan to add more error handing for these soon, just haven't had time yet.  If you let the scan run through these warnings, you should see it complete successfully.

**Comment by Gngester** [comment]
> Those are all just general warnings. The amass error just means amass didn't find any subdomains. I plan to add more error handing for these soon, just haven't had time yet. If you let the scan run through these warnings, you should see it complete successfully.

thanks it was work correctly on kali Linux
