### ISSUE TITLE
framework doesn't run properly in browser

### ISSUE THREAD

**Issue by vishaldalimbe** [R-s0n/ars0n-framework#58]
![image](https://github.com/R-s0n/ars0n-framework/assets/112723215/8e7de8ba-19c0-4ec1-8e1e-8ee8a6cc7bc7)
![ars0n](https://github.com/R-s0n/ars0n-framework/assets/112723215/40cfd707-6039-4179-8576-2e6acd87b111)
this framework does not run properly

**Comment by R-s0n** [comment]
You haven't given me any information that I could use to help you troubleshoot.  Since you also commented in another Issue, I will close this one and continue our conversation there.  I have a question waiting.

**Comment by vishaldalimbe** [comment]
i would like to thank you for fast response.
