### ISSUE TITLE
framework doesn't run properly in browser 

### ISSUE THREAD

**Issue by clipp3rX** [R-s0n/ars0n-framework#59]
![image](https://github.com/R-s0n/ars0n-framework/assets/112723215/5d2d03dc-ded3-4d3d-bb17-79afd832d753)
![Screenshot: 2024-02-15 003515](https://github.com/R-s0n/ars0n-framework/assets/112723215/cf990013-f0bf-4728-b63f-09c5c81ebc49)

Sir, could you please resolve this issue? I have installed this framework in Clein Kali Linux (2023.3), but I cannot get it to run in the browser, and I cannot add domains to the framework. The framework was suddenly stuck, and I cannot operate. If you have solved this issue, I would like to thank you. This framework helps me a lot, and I need it a lot.

**Comment by R-s0n** [comment]
Okay, first, you need to stop spamming this Framework with Issues and comments on other issues.  You are making it incredibly difficult for me to keep track of individual issues.  Other people may have issues that *appear* to be the same of yours, but they are not.  You are causing confusion within our community.

I will repeat my response to one of your many other comments on other issues:

Please provide me with as much information as possible about how your use-case may be unique from other members of the community.  Your PC, virtualization software, processor architecture, anything at all that could help me identify why the framework is not working for you specifically.

I also strongly recommend you review GitHub's Community Guidelines around submitting Issues for open-source projects.  The way you have chosen to conduct yourself here has made it very difficult for me to want to invest my free time helping you succeed.

**Comment by R-s0n** [comment]
@0xmkr24 That question has been answered many times and does not pertain to the original issue.
