### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by TofuWand** [R-s0n/ars0n-framework#60]
Hi. First off, thanks so much for this very advanced security framework, that's 100% free! :3 <3

Well, I've gotten issues pulling files at times, even after turning off my firewall. At one time, it said I had some stuff already in the system, and if I want to replace them, and since I got them from the install of yours, I said no. I'm guessing no error from that. Then it tries to install your framework, and it keeps on failing. I've attached some screenshots and the install log file.

[install.log](https://github.com/R-s0n/ars0n-framework/files/14294071/install.log)

Thanks so much, sir! Shalom. <3 ^_^
![Screenshot_2024-02-12_18_42_48](https://github.com/R-s0n/ars0n-framework/assets/117850518/572a8e1d-8fdf-4760-b79a-3e544fb00b15)
![Screenshot_2024-02-15_17_14_01](https://github.com/R-s0n/ars0n-framework/assets/117850518/dbca2f20-ded1-47c5-ae09-d39cc957bd7f)

**Comment by vishaldalimbe** [comment]
i have also had such problem

**Comment by sTillUnKnoWN-cmd** [comment]
similar problem

**Comment by TofuWand** [comment]
Yeah, no fixes either. I haven't bothered with it since, as the developer
hasn't cared for months. He talks about his framework in his videos he used
to watch, as something he was passionate about, but such a huge issue
getting it, and no fix, nah... Hard pass.

**Comment by R-s0n** [comment]
@TofuWand Wow, what an incredibly rude message.  As I have mentioned many times before, this project is no longer being supported because I am working with a team of engineers to build a new dockerized version of this software that will fix the installation issues.  Please keep in mind that we are volunteers doing this in our free time, we all have families and full time jobs.  I'm genuinely trying my best...

**Comment by TofuWand** [comment]
Now is when you reply to us... It's with a disingenuous, unprofessional
reply, and not a fix to your very broken framework that you clearly don't
care much about.

What an rude reply that you gave, that I didn't read beyond the "rude"
mention for how absurd your behavior is. Haha.

I'll reply regarding your really bad attitude, and lack of care for your
project.

I've had this issue for several months, and others have the same issue.
You're complaining about negative feedback that was done maturely by me,
and others.

If you say so, self-righteous one. You come off as a narcissist, hothead
military member.

You're supposed to be a military member? Grow up. You have ego, superiority
issues. Maybe you're a typical racist White Evangelical, who knows.

It's just me telling the truth of what's going on without any vulgarity.
Grow up. Maybe you're a substance abuser, which makes sense with a lot of
the military.

Garbage framework, clearly, and garbage handling of people supporting your
project and YouTube channel.

Ciao. (;

**Comment by R-s0n** [comment]
I'm very sorry you feel that way and I wish you the best of luck on your bug bounty journey.  God bless.

**Comment by TofuWand** [comment]
Very unfortunate that he claims to be so passionate about a project with a bunch of open issues for several months, and leaves no courtesy that he will get back to us several months later as a so-called professional business person, cyber security worker, and as a military person. Lol. Seriously... Installation issues... 

He's so sensitive that he won't even help his own project to get used by people who cannot even install it in the first place. Sad. Maybe substance abuse or whatever. Who knows. Not a serious project. He doesn't even follow anyone. 

The guy isn't good with people who were very respectful to him. Well, plenty of the military sees excessive anger, abuse, narcissism, PTSD, etc. This is not a steady person when it comes to this GitHub page.

I'm still not caring about reading the replies. There are working frameworks for cyber security on GitHub, for those who even want to use them (many professionals don't). It's nonsensical to stick with this project.

Ciao.

**Comment by R-s0n** [comment]
Sir, your characterization of military veterans (from all countries) and the mental health struggles they endure is highly offensive to me.  I think if you would spend some time with military veterans, you would see that you're assumptions are incorrect.  Again, I wish you the best of luck on your journey.  God Bless.

**Comment by TofuWand** [comment]
That's funny that he addressed me as a sir, even though I never mentioned
my gender at all.

As if females aren't able to do ethical hacking (there are plenty), and as
if there are no famous female ethical hackers (there are plenty). Lol.

That became extra amusing. He's not acting very rational here with his work
that YouTube probably pays him for. All the people dooped into getting this
thing.

I'm glad this isn't a paid for service, as the customer service would be
considered horrible in time, very negative attitude, and not even caring to
fix it. A lot of screwed over people in Google Play reviews by non-caring
developers and scammers.

Again, I'm not reading most of what he says since he put this issue in this
sour direction. This is my last reply to here.

I have plenty of ethical hacking tools from GitHub that work, and I've been
helped by some people in timely manners when I have had issues with their
tools.

Not a working framework for many of us who took the time and data to try to
get the tool to follow along in the video. No fix after several several
months (not several days or several weeks) of these notices to him by
multiple people.

It's blatantly obvious that this is a dead tool. It wasn't really tested or
maintained when before it got on here.

People who are passionate about tools on GitHub can get something like this
fixed in a much shorter time than this.

It's even more so critical when it's part of the person's work, which it
is, since it's part of the YouTube videos that YouTube will pay him for at
a certain criteria.

Negative replies from him instead of telling everyone here that the issue
will be, or will not be worked on. Closing the ticket to something that is
officially broken. 💀

That's someone throwing a fit on many people who have had this problem,
instead of realizing this is a big issue.

The person doesn't want to help, just wants to get really defensive. The
person doesn't want to acknowledge anything good said, only the negative
truth.

He just wants to claim that one isn't allowed to warn others of how he will
promote this non-working framework in his YouTube videos so much. Giving us
this false sense of care for it.

I'm the one who brought up the installation issues that apparently are
going on for others, too.

He's making money on YouTube videos that hold a huge falsity, that there's
care for a working tool. You can follow me in the video once you install my
tool that won't install... Lol. A shame.

Ciao.

**Comment by R-s0n** [comment]
I will pray for you.  I wish you the best of luck.
