### ISSUE TITLE
create dirsearch module on recon

### ISSUE THREAD

**Issue by whitehat92** [R-s0n/ars0n-framework#7]
Hello,
This framework is really wonderful, and I was wondering if it's possible to add in the recon tab, within the list, a category for directory bruteforcing.
Is there an option on node.js when compiling the server to add this?

Thank you so much :)

**Comment by R-s0n** [comment]
I'm so glad you like it!!  And yes, that's actually part of the Enumeration module.  So, the typical workflow with wildfire.py goes like this:

`--start`   Does recon to discover subdomains
`--spread`   Discover hidden web servers running on unusual ports
`--scan`   Wide-band scanning to identify one-off CVEs and other misconfigurations
`--enum`  Directory and parameter brute forcing

I'm going to write up a proper README tonight that will give you a TON more information, but I didn't want to leave you hanging until then :) 

Also, in the next month or so I'll be doing a stream on Twitch to show exactly how to add your own tools to the framework.  That stream will be exported to YouTube, of course, and added to the README as welll.

**Comment by whitehat92** [comment]
Thank you so much, I wasn't aware it was actually included in the --enum phase :D
I'll follow up with your streams as always. Wonderful job, please keep it up :)

**Comment by R-s0n** [comment]
Just to set the right expectations, the --enum scan is still pretty rough, haha!  I promise once I get the --start and --scan modules dial in (Shouldn't be more than a week or two away), I will start digging into that one.  In the meantime, you can have the --start module run all root domains through a Burp proxy and start crawling/enumeration from there.  That's my workflow.  I'll be sure to show that in the stream, too!

Thanks again for the recommendation and I'm so glad your enjoying the content!~
