### ISSUE TITLE
Mongodb instability with Kali builds (With Fix Inside)

### ISSUE THREAD

**Issue by retkoussa** [R-s0n/ars0n-framework#9]
Hey rs0n,

So I've seen previous issues where the FQDN button wouldn't click due to the misconfigured mongod.
The main issue here is that the latest Mongo version is not integrating well with the latest Kali build, so an older version is needed.

Manual installations for Mongo are offered for Debian 10 (buster) only while the latest Kali build is Debian 11 (bullseye); however, the v10 build still works.

I provided the commands below to get it up and running so you can add it to the `install.py` script. If you'd like me to issue a pull request, I'd be more than happy to!

The `mongodb-server-core` package needs to be removed due to a conflict it makes with the `mongodb-org-server`.

```
wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
echo "deb [arch=amd64] https://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" >> /etc/apt/sources.list.d/mongodb-org-4.4.list
sudo apt-get update
sudo apt-get remove mongodb-server-core
sudo apt-get install mongodb-org
sudo systemctl start mongod
sudo systemctl enable mongod
```

This solved the problem for me, I tried all the fixes I can but this seemed to be the most stable.
Cheers!

**Comment by R-s0n** [comment]
Oh, this looks very promising!!  Thank you!!  I've been trying to decide whether to build this out using SQLite instead, but this may be the way to go.  I'll do some testing over the next month or so and get back to you.  

Thanks again!!!

**Comment by R-s0n** [comment]
I had to make a few minor adjustments for the new version of Kali, but it should be up and running.  I'm waiting to hear feedback from others who had issues with Mongo, but the fix seems to be working great.  Thank you again for this!  If you're ever in Houston, I owe you a case of beer 😄

**Comment by retkoussa** [comment]
Been a while! Glad this helped 😄
